### ISSUE TITLE
Broken in Safari 7

### ISSUE THREAD

**Issue by edgesoft** [lsl/xds#2]
I've tested this and with Safari 7 mac this does not work

**Comment by lsl** [comment]
Sorry, didn't see this. I've actually been thinking about giving this thing a new purpose so I should be able to find some time to patch it up / turn it into something a bit more usable, tests etc.

**Comment by lsl** [comment]
Tested safari 7.0.1 seems to work, what was your problem exactly? I've done a bit of a cleanup, added a node express app to run the servers locally. Needs a bit more work but should be pretty easy to setup and try out now.

Let me know if you're still seeing the problem.
